### ISSUE TITLE
При вызове метода pay баланс после проведения платежа не сравнивается с минимально возможным балансом

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#10]
# Описание
При вызове метода **pay** не проверяется, больше ли **остаток на балансе** после платежа, чем **минимальный баланс**.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 2000.
3. Выставить значение переменной minBalance равное 1000.
4. Выставить значение переменной maxBalance равное 15000.
5. Выставить значение переменной rate равное 2.
6. Вызвать метод pay (1500).
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* 2000
*Фактический результат.* 500

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/dd84b8ee-cfd2-4cb2-9e4f-7d8105392859)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/6796e75682a7618b8ad42d03f4d86f22ba5b18cb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L66
