### ISSUE TITLE
После вызова метода add значение баланса становится равным сумме, которая добавляется

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#11]
# Описание
При вызове метода **add** новое значение баланса рассчитывается не как Добавленная сумма + Баланс, а просто становится равным Добавленной сумме.
Этот тест был изначально. Я его только переместил поближе к концу кода. 

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 2000.
3. Выставить значение переменной minBalance равное 1000.
4. Выставить значение переменной maxBalance равное 10000.
5. Выставить значение переменной rate равное 5.
6. Вызвать метод add(3000).
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* 5000
*Фактический результат.* 3000

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/fd863647-06e0-4c64-88b9-44d361aba54e)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/d6eec34093f902424506345a479fe7cf91fec188/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L91
