### ISSUE TITLE
При совершении платежа на сумму выше кредитного лимита, баланс меняется, хотя не должен.

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#12]
# Описание 
При совершении платежа на сумму выше кредитного лимита, метод должен возвращать false и оставлять баланс прежним. False возвращается, но баланс заменяется на сумму платежа со знаком "-". 

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/48149f6744b4a81ad50abf34c792c5a19f71acd4/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 0р.
3.  Совершить платеж на 6_000р.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Баланс становится равным 0р.
*Фактический результат:* Баланс становится равным -6_000р.

# Скриншот
![image](https://github.com/Krideinside/Tournament/assets/129511111/e527f769-1d06-4be6-8c28-5eeb5f06770b)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/48149f6744b4a81ad50abf34c792c5a19f71acd4/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L124

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест теперь проходит.
**balance** перед вычислением теперь проверяется.
