### ISSUE TITLE
При вызове метода **yearChange** процент не рассчитывается при сумме на балансе меньшей, чем 100

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#14]
# Описание
При вызове метода **yearChange** процент не рассчитывается, если значение Баланса было меньше, чем 100.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 89.
3. Выставить значение переменной minBalance равное 0.
4. Выставить значение переменной maxBalance равное 10000.
5. Выставить значение переменной rate равное 5.
6. Вызвать метод yearChange().
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* 4
*Фактический результат.* 0

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/d481f302-61d7-457a-abda-6923899f0b2c)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/13767bed66115da17b2b52f286e79f0fbb9c0e35/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L107
