### ISSUE TITLE
При создании объекта CreditAccount с отрицательным CreditLimit, не выкидывается ошибка

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#15]
# Описание 
При создании объекта CreditAccount с отрицательным CreditLimit, не выкидывается ошибка IllegalArgumentException.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/f4e0475731624b9b8550cf07b97a1246bea4f5cf/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с CreditLimit равным -5_000р.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Выкидывается ошибка IllegalArgumentException.
*Фактический результат:* Ошибка не выкидывается.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/2119f067-407c-4c3a-baa1-7a718482bf9d)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/f4e0475731624b9b8550cf07b97a1246bea4f5cf/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L149

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест теперь проходит.
Добавлена проверка значения creditLimit при создании объекта.
