### ISSUE TITLE
Операция расчёта процентов рассчитывается при положительном балансе, хотя должна быть равна 0

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#16]
# Описание 
Операция расчёта процентов при положительном балансе должна быть равна 0, но операция рассчитывается также, как и с отрицательным балансом.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/f4e0475731624b9b8550cf07b97a1246bea4f5cf/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 1_000р.
3.  Рассчитать годовой процент.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Результат должен быть равен 0.
*Фактический результат:* Результат равен 150.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/38fbed21-dba5-4094-b908-cf97c1ef2592)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/1ccb3748dddd3b1c86f3970f1bdc8672d5a6c912/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L185

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест теперь проходит.
В код метода yearChange была добавлена проверка баланса на отрицательность и немного изменена формула.
