### ISSUE TITLE
Операция расчёта процентов при балансе меньше 100 не рассчитывается.

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#17]
# Описание 

При балансе меньше 100 при делении на 100 по формуле расчета процентов, получаются десятичные дроби,  которые не просчитываются.

# Локация дефекта

https://github.com/Krideinside/javaqa-team-diplom-2/blob/b4e765a8d818e2b27630446c08a661acb1c62d60/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 80р.
3.  Рассчитать годовой процент.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Результат должен быть равен -12.
*Фактический результат:* Результат равен 0.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/a07968fe-fb2e-4e6d-9640-ffb7fd2d0704)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/b4e765a8d818e2b27630446c08a661acb1c62d60/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L185

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест был исправлен.
1. Значение **initialBalance** изменено на 0.
2. Добавлен вызов метода pay(80), чтобы баланс стал отрицательным, чтобы задолженность могла быть  рассчитана.
В код метода **yearChange** была добавлена проверка баланса на отрицательность и немного изменена формула.
