### ISSUE TITLE
Метод установки процентной ставки проходит с отрицательным значением

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#18]
# Описание 
Операция выставления процентной ставки с отрицательным значением проходит, хотя должно выпадать исключение и оставлять предыдущее значение.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/6620a261264a3a60e940f279782eb00cf94d31ed/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L8

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 0р и процентной ставкой 15.
3.  Совершить платеж на 1_000р.
4. Выставить процентную ставку равной "-5".
6.  Запустить программу.
7.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Результат должен быть равен 15.
*Фактический результат:* Результат равен -5.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/d1f51caa-e515-455e-bee6-79ab6ce1bb58)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/6620a261264a3a60e940f279782eb00cf94d31ed/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L257

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест проходит.
Была добавлена проверка на отрицательность.
