### ISSUE TITLE
При создании объекта SavingAccount Баланс не сравнивается с Минимальным балансом

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#2]
# Описание
При создании нового объекта не проверяется условие на то, меньше ли **initialBalance** , чем **minBalance**

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 1000.
3. Выставить значение переменной minBalance равное 2000.
4. Выставить значение переменной maxBalance равное 10000.
5. Выставить значение переменной rate равное 2.
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* Объект не создаётся. Вывод сообщения: IllegalArgumentException
*Фактический результат.* Объект создаётся

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/443bb94d-efd2-4927-9218-347233a7f82f)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/343a92d339a6b24cc4c3fde16fe3c70f531f4516/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L28
