### ISSUE TITLE
При пополнении отрицательного баланса, значение не прибавляется к текущему балансу

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#4]
# Описание 
При совершении пополнения баланса, сумма пополнения заменяет собой баланс при отрицательном текущем балансе.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/1d38dc67d8984d7009ea6bd76b2a7cd32d6614d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 0р.
3.  Совершить платеж на 1_000, чтобы баланс стал отрицательным.
4.  Пополнить счет на 3_000р.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Баланс становится равным 2_000р.
*Фактический результат:* Баланс становится равным 3_000р.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/c555b91b-5a78-4de9-9563-020b1491c58b)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/1d38dc67d8984d7009ea6bd76b2a7cd32d6614d7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L36

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест теперь проходит.
Изменена формула вычисления баланса.
