### ISSUE TITLE
При совершении платежа, сумма платежа не вычитается из баланса при отрицательном балансе

### ISSUE THREAD

**Issue by Krideinside** [Krideinside/javaqa-team-diplom-2#6]
# Описание 
При совершении платежа, сумма не вычитается из баланса, а заменяет баланс своим значением со знаком "-".

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/48149f6744b4a81ad50abf34c792c5a19f71acd4/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2.  Создать объект класса CreditAccount с начальным балансом 0р.
3.  Совершить платеж на 1_000р., чтобы сделать баланс отрицательным.
4.  Совершить платеж на 2_000р.
5.  Запустить программу.
6.  Посмотреть на вывод в консоли.

*Ожидаемый результат:* Баланс становится равным -3_000р.
*Фактический результат:* Баланс становится равным -2_000р.

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129511111/ede267a6-c262-4c89-a4c2-1e322251e238)

# Тест, проверяющий шаги
https://github.com/Krideinside/javaqa-team-diplom-2/blob/1ccb3748dddd3b1c86f3970f1bdc8672d5a6c912/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L88

# Окружение
* **Операционная система:** Windows 11 64bit
*  **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by nhegm** [comment]
Тест теперь проходит.
Изменена формула вычисления баланса.
