### ISSUE TITLE
При создании объекта SavingAccount Максимальный баланс не сравнивается с Минимальным балансом

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#7]
# Описание
При создании нового объекта не проверяется условие на то, больше ли **maxBalance** , чем **minBalance**

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 2000.
3. Выставить значение переменной minBalance равное 10000.
4. Выставить значение переменной maxBalance равное 3000.
5. Выставить значение переменной rate равное 2.
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* Объект не создаётся. Вывод сообщения: IllegalArgumentException
*Фактический результат.* Объект создаётся

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/cc819b70-422e-4440-96b8-b37906cbb09c)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/cbf2bb0609cc09b42f7529a5113e84736953dfda/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L33
