### ISSUE TITLE
При создании объекта SavingAccount Минимальный баланс не проверяется на отрицательное значение

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#8]
# Описание
При создании нового объекта не проверяется условие на то, отрицательное ли значение у **minBalance**

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 2000.
3. Выставить значение переменной minBalance равное -1000.
4. Выставить значение переменной maxBalance равное 15000.
5. Выставить значение переменной rate равное 2.
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* Объект не создаётся. Вывод сообщения: IllegalArgumentException
*Фактический результат.* Объект создаётся

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/cad361bc-7563-4af0-904a-ed034f7ff480)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/8bb9928d48033ad24d3ff74332c0c92355fd9edb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L38
