### ISSUE TITLE
При вызове метода pay сумма платежа не сравнивается с балансом

### ISSUE THREAD

**Issue by nhegm** [Krideinside/javaqa-team-diplom-2#9]
# Описание
При вызове метода **pay** не проверяется, больше ли **сумма платежа**, чем **текущий баланс**.

# Локация дефекта
https://github.com/Krideinside/javaqa-team-diplom-2/blob/5ce7f9d702993eaa0001d085ae2ee49aeea57981/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Krideinside/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной initialBalance равное 2000.
3. Выставить значение переменной minBalance равное 1000.
4. Выставить значение переменной maxBalance равное 15000.
5. Выставить значение переменной rate равное 2.
6. Вызвать метод pay (3000).
7. Запустить программу.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат.* 2000
*Фактический результат.* -1000

# Скриншот
![image](https://github.com/Krideinside/javaqa-team-diplom-2/assets/129392699/e52f0989-ef3b-4071-a69f-1a61d0b609b1)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Krideinside** [comment]
Исправлено
https://github.com/Krideinside/javaqa-team-diplom-2/blob/e101378970ce81d15f69203b241767c4ff8fec63/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L63
